services:
  - type: web
    name: skin-cancer-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python download_models.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
